#!/usr/bin/env python3
"""Generate / refresh the AUTOGENERATED methods table inside GUIDE.md.

The guide (GUIDE.md at the repo root) has two parts:

* Hand-written intro + example request→result pairs. These live OUTSIDE the
  marker comments and are never touched by this script.
* An AUTOGENERATED methods table, rendered between
  ``<!-- TOOLS:AUTO-START -->`` and ``<!-- TOOLS:AUTO-END -->``.

The table is derived from the real ``@mcp.tool()`` registrations in
``ticktick_mcp/src/server.py`` (tool name + a short plain-language description).
Known tools get a curated, obyvatel-friendly Russian description from ``META``
below; any tool that is added / renamed and is NOT yet in ``META`` falls back to
its raw first docstring line and lands in the "Новое / без описания" group — so
a change to the tool set always changes this section.

Usage:
    python scripts/gen_guide.py            # regenerate GUIDE.md in place
    python scripts/gen_guide.py --check    # exit 1 if GUIDE.md is stale

The ``--check`` mode is wired into CI so that editing the tool set without
regenerating the guide fails the build.
"""
from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SERVER_PY = REPO_ROOT / "ticktick_mcp" / "src" / "server.py"
GUIDE_MD = REPO_ROOT / "GUIDE.md"

START_MARKER = "<!-- TOOLS:AUTO-START -->"
END_MARKER = "<!-- TOOLS:AUTO-END -->"

# ---------------------------------------------------------------------------
# Curated, obyvatel-friendly Russian descriptions + theme grouping.
#
# Keyed by tool (function) name. Each value is (theme, "что делает").
# Themes are rendered in THEME_ORDER below. Tools NOT listed here are still
# rendered (from their raw docstring) under "Новое / без описания" — so the
# table can never silently drift from server.py.
# ---------------------------------------------------------------------------
THEME_TASKS = "Задачи (создать, изменить, выполнить, удалить)"
THEME_FIND = "Поиск и готовые списки задач"
THEME_PROJECTS = "Проекты и папки"
THEME_TAGS = "Теги (метки)"
THEME_HABITS = "Привычки"
THEME_COMMENTS = "Комментарии и файлы"
THEME_UTIL = "Служебное и вспомогательное"

THEME_ORDER = [
    THEME_TASKS,
    THEME_FIND,
    THEME_PROJECTS,
    THEME_TAGS,
    THEME_HABITS,
    THEME_COMMENTS,
    THEME_UTIL,
]

# Group used for tools that appear in server.py but are missing from META.
THEME_UNKNOWN = "Новое / без описания (обновите scripts/gen_guide.py)"

META: dict[str, tuple[str, str]] = {
    # --- Задачи -----------------------------------------------------------
    "create_tasks": (THEME_TASKS, "Создать одну или несколько задач, при желании сразу с подзадачами."),
    "create_subtask": (THEME_TASKS, "Добавить подзадачу (пункт) внутри уже существующей задачи."),
    "update_tasks": (THEME_TASKS, "Изменить задачу: название, срок, приоритет, заметку и т. д."),
    "complete_tasks": (THEME_TASKS, "Отметить задачи выполненными (поставить галочку)."),
    "abandon_task": (THEME_TASKS, "Отметить задачу как «не буду делать» (отменить, не удаляя)."),
    "delete_tasks": (THEME_TASKS, "Удалить задачи насовсем (в корзину)."),
    "delete_task_with_subtasks": (THEME_TASKS, "Удалить задачу вместе со всеми её подзадачами разом."),
    "duplicate_task": (THEME_TASKS, "Сделать копию задачи в том же проекте."),
    "move_tasks": (THEME_TASKS, "Перенести задачи в другой список/проект."),
    "set_task_parent": (THEME_TASKS, "Вложить задачи внутрь другой задачи (сделать их подзадачами)."),
    "unset_task_parent": (THEME_TASKS, "Вынуть подзадачу наружу, сделав её обычной задачей."),
    "attach_file_to_task": (THEME_TASKS, "Прикрепить файл к задаче (по ссылке или содержимому)."),
    "plan_task_creation": (THEME_TASKS, "Шаг 1 безопасного создания: показать, что именно будет создано, до подтверждения."),
    "execute_task_creation": (THEME_TASKS, "Шаг 2 безопасного создания: создать ровно то, что было показано в плане."),
    "plan_task_deletion": (THEME_TASKS, "Шаг 1 безопасного удаления: показать, что именно удалится, до подтверждения."),
    "execute_task_deletion": (THEME_TASKS, "Шаг 2 безопасного удаления: удалить ровно то, что было в плане."),
    # --- Поиск и списки ---------------------------------------------------
    "get_task": (THEME_FIND, "Показать подробности одной конкретной задачи."),
    "get_task_info": (THEME_FIND, "Расширенная карточка задачи: все поля, кто создал и когда."),
    "get_all_tasks": (THEME_FIND, "Показать сразу все открытые задачи по всем проектам и Входящим."),
    "get_project_tasks": (THEME_FIND, "Показать задачи внутри одного выбранного проекта."),
    "get_inbox_tasks": (THEME_FIND, "Показать задачи из папки «Входящие»."),
    "get_tasks_due_today": (THEME_FIND, "Что нужно сделать сегодня."),
    "get_tasks_due_tomorrow": (THEME_FIND, "Что нужно сделать завтра."),
    "get_tasks_due_in_days": (THEME_FIND, "Что запланировано ровно через N дней."),
    "get_tasks_due_this_week": (THEME_FIND, "Что запланировано на ближайшую неделю."),
    "get_overdue_tasks": (THEME_FIND, "Показать всё просроченное (сроки уже прошли)."),
    "get_tasks_by_priority": (THEME_FIND, "Показать задачи выбранного приоритета (например, только высокий)."),
    "get_recurring_tasks": (THEME_FIND, "Показать повторяющиеся задачи (те, что возвращаются по расписанию)."),
    "get_engaged_tasks": (THEME_FIND, "Показать задачи, помеченные как «в работе» (Engaged)."),
    "get_next_tasks": (THEME_FIND, "Показать задачи, помеченные как «следующие» (Next)."),
    "get_completed_tasks": (THEME_FIND, "Показать недавно выполненные задачи."),
    "search_tasks": (THEME_FIND, "Найти задачи по словам в названии, заметке или подзадачах."),
    "search_all_tasks": (THEME_FIND, "Расширенный поиск: можно выбрать где искать и как сопоставлять."),
    "get_tasks_by_assignee": (THEME_FIND, "Показать задачи, назначенные конкретному человеку."),
    "list_filters": (THEME_FIND, "Показать сохранённые умные списки (фильтры) и их правила."),
    "run_filter": (THEME_FIND, "Запустить сохранённый умный список и показать подходящие задачи."),
    # --- Проекты ----------------------------------------------------------
    "get_projects": (THEME_PROJECTS, "Показать список всех проектов (списков)."),
    "get_project": (THEME_PROJECTS, "Показать сведения об одном проекте."),
    "create_project": (THEME_PROJECTS, "Создать новый проект (список)."),
    "update_project": (THEME_PROJECTS, "Изменить название, цвет или вид проекта."),
    "delete_project": (THEME_PROJECTS, "Удалить проект насовсем."),
    "archive_project": (THEME_PROJECTS, "Убрать проект в архив или вернуть из архива."),
    "get_project_members": (THEME_PROJECTS, "Показать участников общего проекта (владельца и соавторов)."),
    "list_project_groups": (THEME_PROJECTS, "Показать папки, в которые сгруппированы проекты."),
    "create_project_group": (THEME_PROJECTS, "Создать папку для проектов."),
    "delete_project_group": (THEME_PROJECTS, "Удалить папку (проекты внутри останутся, просто без папки)."),
    "move_project_to_group": (THEME_PROJECTS, "Переложить проект в папку."),
    "list_project_columns": (THEME_PROJECTS, "Показать колонки/разделы (доску) проекта."),
    "create_project_column": (THEME_PROJECTS, "Добавить колонку/раздел на доску проекта."),
    # --- Теги -------------------------------------------------------------
    "list_tags": (THEME_TAGS, "Показать все теги (метки) в аккаунте."),
    "get_tasks_by_tag": (THEME_TAGS, "Показать задачи с определённым тегом."),
    "set_task_tags": (THEME_TAGS, "Заменить набор тегов на задачах."),
    "create_tag": (THEME_TAGS, "Создать новый тег (можно с цветом)."),
    "rename_tag": (THEME_TAGS, "Переименовать тег."),
    "delete_tag": (THEME_TAGS, "Удалить тег (задачи останутся, просто потеряют метку)."),
    # --- Привычки ---------------------------------------------------------
    "get_habits": (THEME_HABITS, "Показать привычки, их цель и текущую серию (стрик)."),
    "checkin_habit": (THEME_HABITS, "Отметить выполнение привычки за день."),
    "get_habit_checkins": (THEME_HABITS, "Показать историю отметок по привычке."),
    # --- Комментарии и файлы ---------------------------------------------
    "get_task_comments": (THEME_COMMENTS, "Показать комментарии к задаче."),
    "add_task_comment": (THEME_COMMENTS, "Добавить комментарий к задаче."),
    "update_task_comment": (THEME_COMMENTS, "Изменить комментарий к задаче."),
    "delete_task_comment": (THEME_COMMENTS, "Удалить комментарий к задаче."),
    # --- Служебное --------------------------------------------------------
    "build_recurrence_rule": (THEME_UTIL, "Собрать правило повторения (например, «каждый вторник») для задачи."),
    "build_reminder": (THEME_UTIL, "Собрать напоминание (например, «за 30 минут до срока»)."),
    "get_statistics": (THEME_UTIL, "Показать статистику продуктивности: очки, уровень, число выполненного."),
    "get_changes": (THEME_UTIL, "Лента изменений: что менялось в аккаунте за период."),
    "get_task_activity": (THEME_UTIL, "История правок конкретной задачи (кто и что менял)."),
    "get_trash": (THEME_UTIL, "Показать содержимое корзины (недавно удалённое)."),
    "restore_tasks": (THEME_UTIL, "Вернуть задачи из корзины."),
    "operation_report": (THEME_UTIL, "Отчёт-проверка после массовой операции: что реально произошло."),
}


def extract_tools(server_src: str) -> list[tuple[str, str]]:
    """Return (name, first_docstring_line) for every @mcp.tool() function."""
    tree = ast.parse(server_src)
    tools: list[tuple[str, str]] = []
    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        for dec in node.decorator_list:
            func = dec.func if isinstance(dec, ast.Call) else dec
            if (
                isinstance(func, ast.Attribute)
                and func.attr == "tool"
                and isinstance(func.value, ast.Name)
                and func.value.id == "mcp"
            ):
                doc = ast.get_docstring(node) or ""
                first = doc.strip().split("\n", 1)[0].strip()
                tools.append((node.name, first))
                break
    return tools


def _clean_fallback(text: str) -> str:
    """Trim a raw docstring line for table use (strip warning glyphs, cap len)."""
    text = text.replace("⚠️", "").strip()
    if len(text) > 120:
        text = text[:117].rstrip() + "…"
    return text or "(без описания)"


def render_table(tools: list[tuple[str, str]]) -> str:
    """Render the autogenerated methods-table section (between the markers)."""
    names = {name for name, _ in tools}

    # Bucket tools by theme, preserving META order within known themes.
    buckets: dict[str, list[tuple[str, str]]] = {t: [] for t in THEME_ORDER}
    buckets[THEME_UNKNOWN] = []

    # Known tools, in META declaration order (so the table order is stable).
    for name, (theme, desc) in META.items():
        if name in names:
            buckets[theme].append((name, desc))

    # Any tool in server.py but missing from META -> unknown bucket.
    for name, first in sorted(tools):
        if name not in META:
            buckets[THEME_UNKNOWN].append((name, _clean_fallback(first)))

    lines: list[str] = []
    lines.append(START_MARKER)
    lines.append("")
    lines.append(
        "> Этот раздел собирается автоматически из кода сервера "
        "(`scripts/gen_guide.py`). Руками не редактируйте — при следующем "
        "запуске генератора правки затрутся."
    )
    lines.append("")
    lines.append(f"**Всего инструментов: {len(tools)}.**")
    lines.append("")

    for theme in [*THEME_ORDER, THEME_UNKNOWN]:
        rows = buckets.get(theme, [])
        if not rows:
            continue
        lines.append(f"### {theme}")
        lines.append("")
        lines.append("| Инструмент | Что делает |")
        lines.append("| --- | --- |")
        for name, desc in rows:
            desc = desc.replace("|", "\\|")
            lines.append(f"| `{name}` | {desc} |")
        lines.append("")

    lines.append(END_MARKER)
    return "\n".join(lines)


HANDWRITTEN_HEADER = """\
# Как пользоваться этим помощником для TickTick

Это руководство для обычного пользователя — без технических терминов.

## Что это такое

TickTick — это приложение для списков дел и задач. Обычно вы открываете его,
находите нужный список, вручную создаёте задачу, ставите срок, приоритет, тег…
Этот «MCP» — мостик, через который **Claude управляет вашим TickTick за вас**.
Вы просто пишете обычными словами, что хотите, а Claude сам нажимает нужные
кнопки внутри TickTick: добавляет задачи, переносит сроки, отмечает выполненное,
раскладывает дела по проектам и тегам, показывает, что горит.

Проще говоря: **вы говорите — Claude делает это в вашем TickTick.**

## Что он умеет (в двух словах)

- Заводить задачи и целые списки дел, в том числе с подзадачами.
- Ставить и переносить сроки, приоритеты, напоминания и повторения
  («каждый понедельник»).
- Отмечать сделанное, отменять и удалять лишнее (с подтверждением перед
  удалением).
- Показывать нужные срезы: что на сегодня, что просрочено, что на неделю,
  что важное.
- Раскладывать дела по проектам (спискам) и папкам, вешать теги.
- Вести привычки, оставлять комментарии к задачам, прикреплять файлы.
- Показывать статистику и историю изменений.

## Когда этим пользоваться

- Когда лень открывать приложение и кликать — быстрее написать словами.
- Когда нужно навести порядок: разобрать входящие, разложить по проектам,
  почистить просроченное.
- Когда хочется быстрый обзор: «что у меня сегодня?», «что я не успел?».
- Когда задача приходит в разговоре — можно сразу попросить занести её.

## Примеры: что написать и что произойдёт

Просто пишите Claude обычными фразами. Вот типичные просьбы и что за ними
следует.

| Вы пишете | Что происходит |
| --- | --- |
| «Добавь задачу купить молоко на завтра с высоким приоритетом» | В TickTick создаётся задача «Купить молоко» со сроком на завтра и высоким приоритетом. |
| «Покажи, что просрочено» | Claude показывает список всех задач, у которых срок уже прошёл. |
| «Что у меня на сегодня?» | Показывается список задач со сроком на сегодняшний день. |
| «Перенеси дедлайн встречи с юристом на пятницу» | Claude находит задачу про встречу и меняет ей срок на ближайшую пятницу. |
| «Отметь, что я оплатил счёт за интернет» | Задача про оплату интернета отмечается выполненной (галочка). |
| «Заведи проект „Ремонт“ и накидай туда: купить краску, вызвать электрика, заказать двери» | Создаётся новый проект «Ремонт», и в него добавляются три задачи. |
| «Сделай задачу „Зарядка“ повторяющейся каждый будний день в 7 утра» | К задаче добавляется повтор по будням с напоминанием на 7:00. |
| «Перенеси все задачи из Входящих в проект „Работа“» | Задачи из папки «Входящие» перемещаются в проект «Работа». |
| «Повесь тег „срочно“ на задачу про отчёт» | На задачу про отчёт вешается метка «срочно». |
| «Удали задачу „позвонить в банк“» | Claude сначала показывает, что именно удалит, и удаляет только после вашего подтверждения. |
| «Как у меня с привычкой „пить воду“ на этой неделе?» | Показывается серия отметок и прогресс по привычке. |
| «Дай короткий обзор: что важного на неделю» | Claude показывает задачи с приоритетом и сроком на ближайшие 7 дней. |

Не нужно помнить точные названия — пишите как удобно, Claude сам подберёт
подходящее действие.

## Полный список действий (методов)

Ниже — таблица всех инструментов, которые Claude может использовать в вашем
TickTick, сгруппированных по темам. Вам не нужно вызывать их вручную; таблица
просто показывает, что «под капотом» умеет помощник. Раздел обновляется
автоматически из кода сервера.

"""


def build_guide(existing: str | None, tools: list[tuple[str, str]]) -> str:
    """Return the full GUIDE.md text with a fresh autogenerated section."""
    auto = render_table(tools)

    if existing and START_MARKER in existing and END_MARKER in existing:
        head, rest = existing.split(START_MARKER, 1)
        _, tail = rest.split(END_MARKER, 1)
        return head + auto + tail

    # No existing file (or markers missing): build from the handwritten header.
    return HANDWRITTEN_HEADER + auto + "\n"


def current_auto_section(text: str) -> str | None:
    if START_MARKER not in text or END_MARKER not in text:
        return None
    start = text.index(START_MARKER)
    end = text.index(END_MARKER) + len(END_MARKER)
    return text[start:end]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if GUIDE.md's autogenerated section is stale.",
    )
    args = parser.parse_args(argv)

    server_src = SERVER_PY.read_text(encoding="utf-8")
    tools = extract_tools(server_src)
    if not tools:
        print("ERROR: no @mcp.tool() functions found in server.py", file=sys.stderr)
        return 2

    existing = GUIDE_MD.read_text(encoding="utf-8") if GUIDE_MD.exists() else None

    if args.check:
        if existing is None:
            print("GUIDE.md is missing. Run: python scripts/gen_guide.py", file=sys.stderr)
            return 1
        expected = render_table(tools)
        actual = current_auto_section(existing)
        if actual != expected:
            print(
                "GUIDE.md is out of date with the MCP tool set.\n"
                "The @mcp.tool() registrations changed but the guide's "
                "autogenerated table was not regenerated.\n"
                "Fix: run `python scripts/gen_guide.py` and commit GUIDE.md.",
                file=sys.stderr,
            )
            return 1
        print(f"GUIDE.md is up to date ({len(tools)} tools).")
        return 0

    new_text = build_guide(existing, tools)
    GUIDE_MD.write_text(new_text, encoding="utf-8")
    print(f"Wrote {GUIDE_MD} ({len(tools)} tools).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
